version: '3.6'
services:
  python:
    build:
      context: .
      dockerfile: ./infra/docker/python/dev/Dockerfile
    container_name: 'python'
    hostname: 'python'
    working_dir: '/opt/work/'
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /opt/work
      - type: bind
        source: ./docs
        target: /opt/docs
    environment:
      TZ: Asia/Tokyo
      LOG_LEVEL: DEBUG
      PROJECT_NAME: docker-python
      SOURCE_VERSION: 1.0.0
      SSH_HOST: ssh-stub
      SSH_PORT: 22
      SSH_USER: root
      SSH_KEY_PATH: "/opt/ssh/id_rsa"
    networks:
      - internal_network_dev

  vscode:
    build:
      context: .
      dockerfile: ./infra/docker/python/dev/Dockerfile
    container_name: 'vscode'
    hostname: 'vscode'
    working_dir: '/home/myzn/repo'
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/myzn/repo
    environment:
      - TZ=Asia/Tokyo

  plantuml:
    image: plantuml/plantuml-server
    container_name: 'plantuml'
    hostname: 'plantuml'
    ports:
      - target: 8080
        published: ${PANTUML_PUBLISHED_PORT:-8080}

  # ssh-stub:
  #   build:
  #     context: .
  #     dockerfile: ./infra/docker/ssh-stub/Dockerfile
  #   container_name: 'ssh-stub'
  #   hostname: 'ssh-stub'
  #   ports:
  #     - target: 22
  #       published: ${SSH_STUB_PUBLISHED_PORT:-22222}
  #   volumes:
  #     - type: bind
  #       source: ./infra/docker/ssh-stub/ssh/id_rsa.pub
  #       target: /root/.ssh/authorized_keys
  #     - type: bind
  #       source: ./infra/docker/ssh-stub/demo_scripts/docker
  #       target: /usr/local/bin/docker
  #   networks:
  #     internal_network_dev:
  #       ipv4_address: 172.21.0.10

networks:
  internal_network_dev:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
