"""common.constant"""

BASE_SRC_PATH = "/opt/work/src"
TITLE = "friends"
SEASON = "s01"
EPISODE = "ep21"

TARGET_EPISODE_PATH = f"{TITLE}/{SEASON}/{EPISODE}"
TARGET_SEASON_PATH = f"{TITLE}/{SEASON}"

TARGET_PATH = TARGET_SEASON_PATH

SUBS_PATH = f"{BASE_SRC_PATH}/subtitles/{TARGET_PATH}"
SUBS_CSV_PATH = f"{BASE_SRC_PATH}/csv/{TARGET_PATH}/subtitles"
VOCABULARY_PATH = f"{BASE_SRC_PATH}/csv/{TARGET_PATH}/vocabularies"
PHRASAL_VERB_PATH = f"{BASE_SRC_PATH}/csv/{TARGET_PATH}/phrasal_verbs"
GROUP_PREPOSITION_PATH = f"{BASE_SRC_PATH}/csv/{TARGET_PATH}/group_prepositions"
FREQUENCY_PATH = f"{BASE_SRC_PATH}/csv/{TARGET_PATH}/frequencies"
